# Example Config File showing various uses of the config

# Host Port
port: 3000

# Protected Containers

protected-containers: ["Caddy", "NTFY"] # List of containers (As printed by Docker ps) that cannot be affected by SOHL

# User configuration

users:
  wife: #Username
    name: Wife # name
    icon: "üë∏" # The icon associated with their username
    level: 2 # Access level (To alter the simplicity of the interface/functionality)
    pet_names: ["honey", "baby"] # List of pet names to get randomized
    theme: cute_pink # Their specific dashboard theme that applies after they pick their username
  kid:
    name: Kid
    icon: "‚öΩÔ∏è"
    level: 1
    pet_names: ["Sport", "Little Homie"]
    theme: matrix